name: Update Main README

on:
  push:
    paths:
      - 'docs/**/*.md'
      - 'src/**/*.js'
      - 'src/**/*.jsx'
      - 'src/**/*.ts'
      - 'src/**/*.tsx'
    branches:
      - master
  schedule:
    - cron: '0 0 * * 1'  # Todos los lunes a medianoche
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Update Main README
        run: |
          python .github/scripts/update_main_readme.py
          
      - name: Commit changes if any
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update main README"
          file_pattern: "README.md"