name: Update Main README

on:
  push:
    paths:
      - 'docs/**/*.md'
      - 'src/**/*.js'
      - 'src/**/*.jsx'
      - 'src/**/*.ts'
      - 'src/**/*.tsx'
    branches:
      - master
  schedule:
    - cron: '0 0 * * 1'  # Todos los lunes a medianoche
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Update Main README
        run: |
          python .github/scripts/update_main_readme.py
          
      - name: Commit changes if any
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update main README"
          git push